dist: trusty
sudo: required
language: node_js

node_js:
  - "10"

cache:
  directories:
    - node_modules

script:
  - npm install

jobs:
  fast_finish: true
  allow_failures:
    - env: SOLIDITY_COVERAGE=true
  include:
    - stage: tests
      name: "unit tests"
      script: npm run test
    - stage: tests
      name: "unit tests with coverage"
      script: npm run test
      env: SOLIDITY_COVERAGE=true

