/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface ClaimProofsContract
  extends Truffle.Contract<ClaimProofsInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<ClaimProofsInstance>;
}

export interface ProofAdded {
  name: "ProofAdded";
  args: {
    coverId: BN;
    owner: string;
    ipfsHash: string;
    0: BN;
    1: string;
    2: string;
  };
}

type AllEvents = ProofAdded;

export interface ClaimProofsInstance extends Truffle.ContractInstance {
  addProof: {
    (
      _coverId: number | BN | string,
      _ipfsHash: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _coverId: number | BN | string,
      _ipfsHash: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _coverId: number | BN | string,
      _ipfsHash: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _coverId: number | BN | string,
      _ipfsHash: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    addProof: {
      (
        _coverId: number | BN | string,
        _ipfsHash: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _coverId: number | BN | string,
        _ipfsHash: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _coverId: number | BN | string,
        _ipfsHash: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _coverId: number | BN | string,
        _ipfsHash: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
