/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface DsValueContract extends Truffle.Contract<DsValueInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<DsValueInstance>;
}

type AllEvents = never;

export interface DsValueInstance extends Truffle.ContractInstance {
  peek(txDetails?: Truffle.TransactionDetails): Promise<[string, boolean]>;

  read(txDetails?: Truffle.TransactionDetails): Promise<string>;

  methods: {
    peek(txDetails?: Truffle.TransactionDetails): Promise<[string, boolean]>;

    read(txDetails?: Truffle.TransactionDetails): Promise<string>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
