/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface GovernanceContract
  extends Truffle.Contract<GovernanceInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<GovernanceInstance>;
}

export interface ActionFailed {
  name: "ActionFailed";
  args: {
    proposalId: BN;
    0: BN;
  };
}

export interface ActionRejected {
  name: "ActionRejected";
  args: {
    proposalId: BN;
    rejectedBy: string;
    0: BN;
    1: string;
  };
}

export interface ActionSuccess {
  name: "ActionSuccess";
  args: {
    proposalId: BN;
    0: BN;
  };
}

export interface CloseProposalOnTime {
  name: "CloseProposalOnTime";
  args: {
    proposalId: BN;
    time: BN;
    0: BN;
    1: BN;
  };
}

export interface Proposal {
  name: "Proposal";
  args: {
    proposalOwner: string;
    proposalId: BN;
    dateAdd: BN;
    proposalTitle: string;
    proposalSD: string;
    proposalDescHash: string;
    0: string;
    1: BN;
    2: BN;
    3: string;
    4: string;
    5: string;
  };
}

export interface ProposalAccepted {
  name: "ProposalAccepted";
  args: {
    proposalId: BN;
    0: BN;
  };
}

export interface ProposalCategorized {
  name: "ProposalCategorized";
  args: {
    proposalId: BN;
    categorizedBy: string;
    categoryId: BN;
    0: BN;
    1: string;
    2: BN;
  };
}

export interface RewardClaimed {
  name: "RewardClaimed";
  args: {
    member: string;
    gbtReward: BN;
    0: string;
    1: BN;
  };
}

export interface Solution {
  name: "Solution";
  args: {
    proposalId: BN;
    solutionOwner: string;
    solutionId: BN;
    solutionDescHash: string;
    dateAdd: BN;
    0: BN;
    1: string;
    2: BN;
    3: string;
    4: BN;
  };
}

export interface Vote {
  name: "Vote";
  args: {
    from: string;
    proposalId: BN;
    voteId: BN;
    dateAdd: BN;
    solutionChosen: BN;
    0: string;
    1: BN;
    2: BN;
    3: BN;
    4: BN;
  };
}

export interface VoteCast {
  name: "VoteCast";
  args: {
    proposalId: BN;
    0: BN;
  };
}

type AllEvents =
  | ActionFailed
  | ActionRejected
  | ActionSuccess
  | CloseProposalOnTime
  | Proposal
  | ProposalAccepted
  | ProposalCategorized
  | RewardClaimed
  | Solution
  | Vote
  | VoteCast;

export interface GovernanceInstance extends Truffle.ContractInstance {
  allDelegation(
    arg0: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<[string, string, BN]>;

  allowedToCatgorize(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  allowedToCreateProposal(
    category: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  alreadyDelegated(
    _add: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  canCloseProposal(
    _proposalId: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  categorizeProposal: {
    (
      _proposalId: number | BN | string,
      _categoryId: number | BN | string,
      _incentive: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _proposalId: number | BN | string,
      _categoryId: number | BN | string,
      _incentive: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _proposalId: number | BN | string,
      _categoryId: number | BN | string,
      _incentive: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _proposalId: number | BN | string,
      _categoryId: number | BN | string,
      _incentive: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  changeDependentContractAddress: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  changeMasterAddress: {
    (_masterAddress: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      _masterAddress: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _masterAddress: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _masterAddress: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  claimReward: {
    (
      _memberAddress: string,
      _maxRecords: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _memberAddress: string,
      _maxRecords: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;
    sendTransaction(
      _memberAddress: string,
      _maxRecords: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _memberAddress: string,
      _maxRecords: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  closeProposal: {
    (
      _proposalId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _proposalId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _proposalId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _proposalId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  createProposal: {
    (
      _proposalTitle: string,
      _proposalSD: string,
      _proposalDescHash: string,
      _categoryId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _proposalTitle: string,
      _proposalSD: string,
      _proposalDescHash: string,
      _categoryId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _proposalTitle: string,
      _proposalSD: string,
      _proposalDescHash: string,
      _categoryId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _proposalTitle: string,
      _proposalSD: string,
      _proposalDescHash: string,
      _categoryId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  createProposalwithSolution: {
    (
      _proposalTitle: string,
      _proposalSD: string,
      _proposalDescHash: string,
      _categoryId: number | BN | string,
      _solutionHash: string,
      _action: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _proposalTitle: string,
      _proposalSD: string,
      _proposalDescHash: string,
      _categoryId: number | BN | string,
      _solutionHash: string,
      _action: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _proposalTitle: string,
      _proposalSD: string,
      _proposalDescHash: string,
      _categoryId: number | BN | string,
      _solutionHash: string,
      _action: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _proposalTitle: string,
      _proposalSD: string,
      _proposalDescHash: string,
      _categoryId: number | BN | string,
      _solutionHash: string,
      _action: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  delegateVote: {
    (_add: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(_add: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(
      _add: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _add: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  followerDelegation(
    arg0: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  getFollowers(
    _add: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN[]>;

  getPendingReward(
    _memberAddress: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  getProposalLength(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  getSolutionAction(
    _proposalId: number | BN | string,
    _solution: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<[BN, string]>;

  getUintParameters(
    code: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<[string, BN]>;

  isOpenForDelegation(
    arg0: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  lastRewardClaimed(
    arg0: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  memberProposalVote(
    arg0: string,
    arg1: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  ms(txDetails?: Truffle.TransactionDetails): Promise<string>;

  nxMasterAddress(txDetails?: Truffle.TransactionDetails): Promise<string>;

  proposal(
    _proposalId: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<[BN, BN, BN, BN, BN]>;

  proposalActionStatus(
    arg0: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  proposalDetails(
    _proposalId: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<[BN, BN, BN]>;

  proposalRejectedByAB(
    arg0: number | BN | string,
    arg1: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  proposalVoteTally(
    arg0: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  rejectAction: {
    (
      _proposalId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _proposalId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _proposalId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _proposalId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  removeDelegation: {
    (_add: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(_add: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(
      _add: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _add: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  rewardClaimed(
    arg0: number | BN | string,
    arg1: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  setDelegationStatus: {
    (_status: boolean, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      _status: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _status: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _status: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  setInitialActionParameters: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  submitProposalWithSolution: {
    (
      _proposalId: number | BN | string,
      _solutionHash: string,
      _action: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _proposalId: number | BN | string,
      _solutionHash: string,
      _action: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _proposalId: number | BN | string,
      _solutionHash: string,
      _action: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _proposalId: number | BN | string,
      _solutionHash: string,
      _action: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  submitVote: {
    (
      _proposalId: number | BN | string,
      _solutionChosen: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _proposalId: number | BN | string,
      _solutionChosen: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _proposalId: number | BN | string,
      _solutionChosen: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _proposalId: number | BN | string,
      _solutionChosen: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  tokenHoldingTime(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  triggerAction: {
    (
      _proposalId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _proposalId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _proposalId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _proposalId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  unDelegate: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  updateProposal: {
    (
      _proposalId: number | BN | string,
      _proposalTitle: string,
      _proposalSD: string,
      _proposalDescHash: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _proposalId: number | BN | string,
      _proposalTitle: string,
      _proposalSD: string,
      _proposalDescHash: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _proposalId: number | BN | string,
      _proposalTitle: string,
      _proposalSD: string,
      _proposalDescHash: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _proposalId: number | BN | string,
      _proposalTitle: string,
      _proposalSD: string,
      _proposalDescHash: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  updateUintParameters: {
    (
      code: string,
      val: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      code: string,
      val: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      code: string,
      val: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      code: string,
      val: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  voteTallyData(
    _proposalId: number | BN | string,
    _solution: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<[BN, BN, BN]>;

  methods: {
    allDelegation(
      arg0: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<[string, string, BN]>;

    allowedToCatgorize(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    allowedToCreateProposal(
      category: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    alreadyDelegated(
      _add: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    canCloseProposal(
      _proposalId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    categorizeProposal: {
      (
        _proposalId: number | BN | string,
        _categoryId: number | BN | string,
        _incentive: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _proposalId: number | BN | string,
        _categoryId: number | BN | string,
        _incentive: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _proposalId: number | BN | string,
        _categoryId: number | BN | string,
        _incentive: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _proposalId: number | BN | string,
        _categoryId: number | BN | string,
        _incentive: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    changeDependentContractAddress: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };

    changeMasterAddress: {
      (_masterAddress: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        _masterAddress: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _masterAddress: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _masterAddress: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    claimReward: {
      (
        _memberAddress: string,
        _maxRecords: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _memberAddress: string,
        _maxRecords: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<BN>;
      sendTransaction(
        _memberAddress: string,
        _maxRecords: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _memberAddress: string,
        _maxRecords: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    closeProposal: {
      (
        _proposalId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _proposalId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _proposalId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _proposalId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    createProposal: {
      (
        _proposalTitle: string,
        _proposalSD: string,
        _proposalDescHash: string,
        _categoryId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _proposalTitle: string,
        _proposalSD: string,
        _proposalDescHash: string,
        _categoryId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _proposalTitle: string,
        _proposalSD: string,
        _proposalDescHash: string,
        _categoryId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _proposalTitle: string,
        _proposalSD: string,
        _proposalDescHash: string,
        _categoryId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    createProposalwithSolution: {
      (
        _proposalTitle: string,
        _proposalSD: string,
        _proposalDescHash: string,
        _categoryId: number | BN | string,
        _solutionHash: string,
        _action: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _proposalTitle: string,
        _proposalSD: string,
        _proposalDescHash: string,
        _categoryId: number | BN | string,
        _solutionHash: string,
        _action: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _proposalTitle: string,
        _proposalSD: string,
        _proposalDescHash: string,
        _categoryId: number | BN | string,
        _solutionHash: string,
        _action: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _proposalTitle: string,
        _proposalSD: string,
        _proposalDescHash: string,
        _categoryId: number | BN | string,
        _solutionHash: string,
        _action: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    delegateVote: {
      (_add: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(_add: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(
        _add: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _add: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    followerDelegation(
      arg0: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    getFollowers(
      _add: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN[]>;

    getPendingReward(
      _memberAddress: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    getProposalLength(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    getSolutionAction(
      _proposalId: number | BN | string,
      _solution: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<[BN, string]>;

    getUintParameters(
      code: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<[string, BN]>;

    isOpenForDelegation(
      arg0: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    lastRewardClaimed(
      arg0: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    memberProposalVote(
      arg0: string,
      arg1: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    ms(txDetails?: Truffle.TransactionDetails): Promise<string>;

    nxMasterAddress(txDetails?: Truffle.TransactionDetails): Promise<string>;

    proposal(
      _proposalId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<[BN, BN, BN, BN, BN]>;

    proposalActionStatus(
      arg0: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    proposalDetails(
      _proposalId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<[BN, BN, BN]>;

    proposalRejectedByAB(
      arg0: number | BN | string,
      arg1: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    proposalVoteTally(
      arg0: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    rejectAction: {
      (
        _proposalId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _proposalId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _proposalId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _proposalId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    removeDelegation: {
      (_add: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(_add: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(
        _add: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _add: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    rewardClaimed(
      arg0: number | BN | string,
      arg1: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    setDelegationStatus: {
      (_status: boolean, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        _status: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _status: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _status: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    setInitialActionParameters: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };

    submitProposalWithSolution: {
      (
        _proposalId: number | BN | string,
        _solutionHash: string,
        _action: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _proposalId: number | BN | string,
        _solutionHash: string,
        _action: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _proposalId: number | BN | string,
        _solutionHash: string,
        _action: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _proposalId: number | BN | string,
        _solutionHash: string,
        _action: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    submitVote: {
      (
        _proposalId: number | BN | string,
        _solutionChosen: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _proposalId: number | BN | string,
        _solutionChosen: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _proposalId: number | BN | string,
        _solutionChosen: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _proposalId: number | BN | string,
        _solutionChosen: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    tokenHoldingTime(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    triggerAction: {
      (
        _proposalId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _proposalId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _proposalId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _proposalId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    unDelegate: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };

    updateProposal: {
      (
        _proposalId: number | BN | string,
        _proposalTitle: string,
        _proposalSD: string,
        _proposalDescHash: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _proposalId: number | BN | string,
        _proposalTitle: string,
        _proposalSD: string,
        _proposalDescHash: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _proposalId: number | BN | string,
        _proposalTitle: string,
        _proposalSD: string,
        _proposalDescHash: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _proposalId: number | BN | string,
        _proposalTitle: string,
        _proposalSD: string,
        _proposalDescHash: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    updateUintParameters: {
      (
        code: string,
        val: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        code: string,
        val: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        code: string,
        val: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        code: string,
        val: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    voteTallyData(
      _proposalId: number | BN | string,
      _solution: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<[BN, BN, BN]>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
