/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ContextContract } from "./Context";
import { Erc20Contract } from "./Erc20";
import { Ierc20Contract } from "./Ierc20";
import { InxmMasterContract } from "./InxmMaster";
import { InxmTokenContract } from "./InxmToken";
import { IupgradableContract } from "./Iupgradable";
import { MasterAwareContract } from "./MasterAware";
import { DeployerContract } from "./Deployer";
import { OraclizeAddrResolverIContract } from "./OraclizeAddrResolverI";
import { OraclizeIContract } from "./OraclizeI";
import { SolcCheckerContract } from "./SolcChecker";
import { UsingOraclizeContract } from "./UsingOraclize";
import { ExchangeContract } from "./Exchange";
import { FactoryContract } from "./Factory";
import { IClaimsRewardContract } from "./IClaimsReward";
import { IMasterAwareContract } from "./IMasterAware";
import { IMemberRolesContract } from "./IMemberRoles";
import { IPooledStakingContract } from "./IPooledStaking";
import { ITokenControllerContract } from "./ITokenController";
import { ITokenDataContract } from "./ITokenData";
import { ITokenFunctionsContract } from "./ITokenFunctions";
import { DisposableGovernanceContract } from "./DisposableGovernance";
import { DisposableMemberRolesContract } from "./DisposableMemberRoles";
import { DisposableNxMasterContract } from "./DisposableNxMaster";
import { DisposablePooledStakingContract } from "./DisposablePooledStaking";
import { DisposableProposalCategoryContract } from "./DisposableProposalCategory";
import { DisposableTokenControllerContract } from "./DisposableTokenController";
import { Erc20MockContract } from "./Erc20Mock";
import { ExchangeFactoryMockContract } from "./ExchangeFactoryMock";
import { ExchangeMockContract } from "./ExchangeMock";
import { MasterMockContract } from "./MasterMock";
import { MemberRolesMockContract } from "./MemberRolesMock";
import { NxmdsValueMockContract } from "./NxmdsValueMock";
import { NxmTokenMockContract } from "./NxmTokenMock";
import { Pool1MockContract } from "./Pool1Mock";
import { TokenControllerMockContract } from "./TokenControllerMock";
import { McrContract } from "./Mcr";
import { AggregatorContract } from "./Aggregator";
import { NxmdsValueContract } from "./NxmdsValue";
import { Pool1Contract } from "./Pool1";
import { Pool2Contract } from "./Pool2";
import { DsValueContract } from "./DsValue";
import { PoolDataContract } from "./PoolData";
import { ClaimProofsContract } from "./ClaimProofs";
import { ClaimsContract } from "./Claims";
import { ClaimsDataContract } from "./ClaimsData";
import { ClaimsRewardContract } from "./ClaimsReward";
import { QuotationContract } from "./Quotation";
import { QuotationDataContract } from "./QuotationData";
import { GovernedContract } from "./Governed";
import { IMasterContract } from "./IMaster";
import { IGovernanceContract } from "./IGovernance";
import { IProposalCategoryContract } from "./IProposalCategory";
import { OwnedUpgradeabilityProxyContract } from "./OwnedUpgradeabilityProxy";
import { ProxyContract } from "./Proxy";
import { UpgradeabilityProxyContract } from "./UpgradeabilityProxy";
import { GovernanceContract } from "./Governance";
import { MemberRolesContract } from "./MemberRoles";
import { NxMasterContract } from "./NxMaster";
import { ProposalCategoryContract } from "./ProposalCategory";
import { PooledStakingContract } from "./PooledStaking";
import { Ierc1132Contract } from "./Ierc1132";
import { Ozierc20Contract } from "./Ozierc20";
import { NxmTokenContract } from "./NxmToken";
import { TokenControllerContract } from "./TokenController";
import { TokenDataContract } from "./TokenData";
import { TokenFunctionsContract } from "./TokenFunctions";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Context"): ContextContract;
      require(name: "ERC20"): Erc20Contract;
      require(name: "IERC20"): Ierc20Contract;
      require(name: "INXMMaster"): InxmMasterContract;
      require(name: "INXMToken"): InxmTokenContract;
      require(name: "Iupgradable"): IupgradableContract;
      require(name: "MasterAware"): MasterAwareContract;
      require(name: "Deployer"): DeployerContract;
      require(name: "OraclizeAddrResolverI"): OraclizeAddrResolverIContract;
      require(name: "OraclizeI"): OraclizeIContract;
      require(name: "solcChecker"): SolcCheckerContract;
      require(name: "usingOraclize"): UsingOraclizeContract;
      require(name: "Exchange"): ExchangeContract;
      require(name: "Factory"): FactoryContract;
      require(name: "IClaimsReward"): IClaimsRewardContract;
      require(name: "IMasterAware"): IMasterAwareContract;
      require(name: "IMemberRoles"): IMemberRolesContract;
      require(name: "IPooledStaking"): IPooledStakingContract;
      require(name: "ITokenController"): ITokenControllerContract;
      require(name: "ITokenData"): ITokenDataContract;
      require(name: "ITokenFunctions"): ITokenFunctionsContract;
      require(name: "DisposableGovernance"): DisposableGovernanceContract;
      require(name: "DisposableMemberRoles"): DisposableMemberRolesContract;
      require(name: "DisposableNXMaster"): DisposableNxMasterContract;
      require(name: "DisposablePooledStaking"): DisposablePooledStakingContract;
      require(
        name: "DisposableProposalCategory"
      ): DisposableProposalCategoryContract;
      require(
        name: "DisposableTokenController"
      ): DisposableTokenControllerContract;
      require(name: "ERC20Mock"): Erc20MockContract;
      require(name: "ExchangeFactoryMock"): ExchangeFactoryMockContract;
      require(name: "ExchangeMock"): ExchangeMockContract;
      require(name: "MasterMock"): MasterMockContract;
      require(name: "MemberRolesMock"): MemberRolesMockContract;
      require(name: "NXMDSValueMock"): NxmdsValueMockContract;
      require(name: "NXMTokenMock"): NxmTokenMockContract;
      require(name: "Pool1Mock"): Pool1MockContract;
      require(name: "TokenControllerMock"): TokenControllerMockContract;
      require(name: "MCR"): McrContract;
      require(name: "Aggregator"): AggregatorContract;
      require(name: "NXMDSValue"): NxmdsValueContract;
      require(name: "Pool1"): Pool1Contract;
      require(name: "Pool2"): Pool2Contract;
      require(name: "DSValue"): DsValueContract;
      require(name: "PoolData"): PoolDataContract;
      require(name: "ClaimProofs"): ClaimProofsContract;
      require(name: "Claims"): ClaimsContract;
      require(name: "ClaimsData"): ClaimsDataContract;
      require(name: "ClaimsReward"): ClaimsRewardContract;
      require(name: "Quotation"): QuotationContract;
      require(name: "QuotationData"): QuotationDataContract;
      require(name: "Governed"): GovernedContract;
      require(name: "IMaster"): IMasterContract;
      require(name: "IGovernance"): IGovernanceContract;
      require(name: "IProposalCategory"): IProposalCategoryContract;
      require(
        name: "OwnedUpgradeabilityProxy"
      ): OwnedUpgradeabilityProxyContract;
      require(name: "Proxy"): ProxyContract;
      require(name: "UpgradeabilityProxy"): UpgradeabilityProxyContract;
      require(name: "Governance"): GovernanceContract;
      require(name: "MemberRoles"): MemberRolesContract;
      require(name: "NXMaster"): NxMasterContract;
      require(name: "ProposalCategory"): ProposalCategoryContract;
      require(name: "PooledStaking"): PooledStakingContract;
      require(name: "IERC1132"): Ierc1132Contract;
      require(name: "OZIERC20"): Ozierc20Contract;
      require(name: "NXMToken"): NxmTokenContract;
      require(name: "TokenController"): TokenControllerContract;
      require(name: "TokenData"): TokenDataContract;
      require(name: "TokenFunctions"): TokenFunctionsContract;
    }
  }
}

export { ContextContract, ContextInstance } from "./Context";
export { Erc20Contract, Erc20Instance } from "./Erc20";
export { Ierc20Contract, Ierc20Instance } from "./Ierc20";
export { InxmMasterContract, InxmMasterInstance } from "./InxmMaster";
export { InxmTokenContract, InxmTokenInstance } from "./InxmToken";
export { IupgradableContract, IupgradableInstance } from "./Iupgradable";
export { MasterAwareContract, MasterAwareInstance } from "./MasterAware";
export { DeployerContract, DeployerInstance } from "./Deployer";
export {
  OraclizeAddrResolverIContract,
  OraclizeAddrResolverIInstance,
} from "./OraclizeAddrResolverI";
export { OraclizeIContract, OraclizeIInstance } from "./OraclizeI";
export { SolcCheckerContract, SolcCheckerInstance } from "./SolcChecker";
export { UsingOraclizeContract, UsingOraclizeInstance } from "./UsingOraclize";
export { ExchangeContract, ExchangeInstance } from "./Exchange";
export { FactoryContract, FactoryInstance } from "./Factory";
export { IClaimsRewardContract, IClaimsRewardInstance } from "./IClaimsReward";
export { IMasterAwareContract, IMasterAwareInstance } from "./IMasterAware";
export { IMemberRolesContract, IMemberRolesInstance } from "./IMemberRoles";
export {
  IPooledStakingContract,
  IPooledStakingInstance,
} from "./IPooledStaking";
export {
  ITokenControllerContract,
  ITokenControllerInstance,
} from "./ITokenController";
export { ITokenDataContract, ITokenDataInstance } from "./ITokenData";
export {
  ITokenFunctionsContract,
  ITokenFunctionsInstance,
} from "./ITokenFunctions";
export {
  DisposableGovernanceContract,
  DisposableGovernanceInstance,
} from "./DisposableGovernance";
export {
  DisposableMemberRolesContract,
  DisposableMemberRolesInstance,
} from "./DisposableMemberRoles";
export {
  DisposableNxMasterContract,
  DisposableNxMasterInstance,
} from "./DisposableNxMaster";
export {
  DisposablePooledStakingContract,
  DisposablePooledStakingInstance,
} from "./DisposablePooledStaking";
export {
  DisposableProposalCategoryContract,
  DisposableProposalCategoryInstance,
} from "./DisposableProposalCategory";
export {
  DisposableTokenControllerContract,
  DisposableTokenControllerInstance,
} from "./DisposableTokenController";
export { Erc20MockContract, Erc20MockInstance } from "./Erc20Mock";
export {
  ExchangeFactoryMockContract,
  ExchangeFactoryMockInstance,
} from "./ExchangeFactoryMock";
export { ExchangeMockContract, ExchangeMockInstance } from "./ExchangeMock";
export { MasterMockContract, MasterMockInstance } from "./MasterMock";
export {
  MemberRolesMockContract,
  MemberRolesMockInstance,
} from "./MemberRolesMock";
export {
  NxmdsValueMockContract,
  NxmdsValueMockInstance,
} from "./NxmdsValueMock";
export { NxmTokenMockContract, NxmTokenMockInstance } from "./NxmTokenMock";
export { Pool1MockContract, Pool1MockInstance } from "./Pool1Mock";
export {
  TokenControllerMockContract,
  TokenControllerMockInstance,
} from "./TokenControllerMock";
export { McrContract, McrInstance } from "./Mcr";
export { AggregatorContract, AggregatorInstance } from "./Aggregator";
export { NxmdsValueContract, NxmdsValueInstance } from "./NxmdsValue";
export { Pool1Contract, Pool1Instance } from "./Pool1";
export { Pool2Contract, Pool2Instance } from "./Pool2";
export { DsValueContract, DsValueInstance } from "./DsValue";
export { PoolDataContract, PoolDataInstance } from "./PoolData";
export { ClaimProofsContract, ClaimProofsInstance } from "./ClaimProofs";
export { ClaimsContract, ClaimsInstance } from "./Claims";
export { ClaimsDataContract, ClaimsDataInstance } from "./ClaimsData";
export { ClaimsRewardContract, ClaimsRewardInstance } from "./ClaimsReward";
export { QuotationContract, QuotationInstance } from "./Quotation";
export { QuotationDataContract, QuotationDataInstance } from "./QuotationData";
export { GovernedContract, GovernedInstance } from "./Governed";
export { IMasterContract, IMasterInstance } from "./IMaster";
export { IGovernanceContract, IGovernanceInstance } from "./IGovernance";
export {
  IProposalCategoryContract,
  IProposalCategoryInstance,
} from "./IProposalCategory";
export {
  OwnedUpgradeabilityProxyContract,
  OwnedUpgradeabilityProxyInstance,
} from "./OwnedUpgradeabilityProxy";
export { ProxyContract, ProxyInstance } from "./Proxy";
export {
  UpgradeabilityProxyContract,
  UpgradeabilityProxyInstance,
} from "./UpgradeabilityProxy";
export { GovernanceContract, GovernanceInstance } from "./Governance";
export { MemberRolesContract, MemberRolesInstance } from "./MemberRoles";
export { NxMasterContract, NxMasterInstance } from "./NxMaster";
export {
  ProposalCategoryContract,
  ProposalCategoryInstance,
} from "./ProposalCategory";
export { PooledStakingContract, PooledStakingInstance } from "./PooledStaking";
export { Ierc1132Contract, Ierc1132Instance } from "./Ierc1132";
export { Ozierc20Contract, Ozierc20Instance } from "./Ozierc20";
export { NxmTokenContract, NxmTokenInstance } from "./NxmToken";
export {
  TokenControllerContract,
  TokenControllerInstance,
} from "./TokenController";
export { TokenDataContract, TokenDataInstance } from "./TokenData";
export {
  TokenFunctionsContract,
  TokenFunctionsInstance,
} from "./TokenFunctions";
