/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface QuotationContract extends Truffle.Contract<QuotationInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<QuotationInstance>;
}

type AllEvents = never;

export interface QuotationInstance extends Truffle.ContractInstance {
  changeDependentContractAddress: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  changeMasterAddress: {
    (masterAddress: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      masterAddress: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      masterAddress: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      masterAddress: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  cr(txDetails?: Truffle.TransactionDetails): Promise<string>;

  createCover: {
    (
      from: string,
      scAddress: string,
      currency: string,
      coverDetails: (number | BN | string)[],
      coverPeriod: number | BN | string,
      _v: number | BN | string,
      _r: string,
      _s: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      from: string,
      scAddress: string,
      currency: string,
      coverDetails: (number | BN | string)[],
      coverPeriod: number | BN | string,
      _v: number | BN | string,
      _r: string,
      _s: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      from: string,
      scAddress: string,
      currency: string,
      coverDetails: (number | BN | string)[],
      coverPeriod: number | BN | string,
      _v: number | BN | string,
      _r: string,
      _s: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      from: string,
      scAddress: string,
      currency: string,
      coverDetails: (number | BN | string)[],
      coverPeriod: number | BN | string,
      _v: number | BN | string,
      _r: string,
      _s: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  expireCover: {
    (
      coverId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      coverId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      coverId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      coverId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  freeUpHeldCovers: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  getOrderHash(
    coverDetails: (number | BN | string)[],
    coverPeriod: number | BN | string,
    currency: string,
    contractAddress: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  getWithdrawableCoverNoteCoverIds(
    coverOwner: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<[BN[], string[]]>;

  getWithdrawableCoverNotesAmount(
    coverOwner: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  incidents(txDetails?: Truffle.TransactionDetails): Promise<string>;

  isValidSignature(
    hash: string,
    v: number | BN | string,
    r: string,
    s: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  makeCoverUsingNXMTokens: {
    (
      coverDetails: (number | BN | string)[],
      coverPeriod: number | BN | string,
      coverCurr: string,
      smartCAdd: string,
      _v: number | BN | string,
      _r: string,
      _s: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      coverDetails: (number | BN | string)[],
      coverPeriod: number | BN | string,
      coverCurr: string,
      smartCAdd: string,
      _v: number | BN | string,
      _r: string,
      _s: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      coverDetails: (number | BN | string)[],
      coverPeriod: number | BN | string,
      coverCurr: string,
      smartCAdd: string,
      _v: number | BN | string,
      _r: string,
      _s: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      coverDetails: (number | BN | string)[],
      coverPeriod: number | BN | string,
      coverCurr: string,
      smartCAdd: string,
      _v: number | BN | string,
      _r: string,
      _s: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  master(txDetails?: Truffle.TransactionDetails): Promise<string>;

  pool(txDetails?: Truffle.TransactionDetails): Promise<string>;

  pooledStaking(txDetails?: Truffle.TransactionDetails): Promise<string>;

  qd(txDetails?: Truffle.TransactionDetails): Promise<string>;

  sendEther: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  tc(txDetails?: Truffle.TransactionDetails): Promise<string>;

  td(txDetails?: Truffle.TransactionDetails): Promise<string>;

  transferAssetsToNewContract(
    arg0: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<void>;

  verifyCoverDetails: {
    (
      from: string,
      scAddress: string,
      coverCurr: string,
      coverDetails: (number | BN | string)[],
      coverPeriod: number | BN | string,
      _v: number | BN | string,
      _r: string,
      _s: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      from: string,
      scAddress: string,
      coverCurr: string,
      coverDetails: (number | BN | string)[],
      coverPeriod: number | BN | string,
      _v: number | BN | string,
      _r: string,
      _s: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      from: string,
      scAddress: string,
      coverCurr: string,
      coverDetails: (number | BN | string)[],
      coverPeriod: number | BN | string,
      _v: number | BN | string,
      _r: string,
      _s: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      from: string,
      scAddress: string,
      coverCurr: string,
      coverDetails: (number | BN | string)[],
      coverPeriod: number | BN | string,
      _v: number | BN | string,
      _r: string,
      _s: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  verifySignature(
    coverDetails: (number | BN | string)[],
    coverPeriod: number | BN | string,
    currency: string,
    contractAddress: string,
    _v: number | BN | string,
    _r: string,
    _s: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  withdrawCoverNote: {
    (
      coverOwner: string,
      coverIds: (number | BN | string)[],
      reasonIndexes: (number | BN | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      coverOwner: string,
      coverIds: (number | BN | string)[],
      reasonIndexes: (number | BN | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      coverOwner: string,
      coverIds: (number | BN | string)[],
      reasonIndexes: (number | BN | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      coverOwner: string,
      coverIds: (number | BN | string)[],
      reasonIndexes: (number | BN | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    changeDependentContractAddress: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };

    changeMasterAddress: {
      (masterAddress: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        masterAddress: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        masterAddress: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        masterAddress: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    cr(txDetails?: Truffle.TransactionDetails): Promise<string>;

    createCover: {
      (
        from: string,
        scAddress: string,
        currency: string,
        coverDetails: (number | BN | string)[],
        coverPeriod: number | BN | string,
        _v: number | BN | string,
        _r: string,
        _s: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        from: string,
        scAddress: string,
        currency: string,
        coverDetails: (number | BN | string)[],
        coverPeriod: number | BN | string,
        _v: number | BN | string,
        _r: string,
        _s: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        from: string,
        scAddress: string,
        currency: string,
        coverDetails: (number | BN | string)[],
        coverPeriod: number | BN | string,
        _v: number | BN | string,
        _r: string,
        _s: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        from: string,
        scAddress: string,
        currency: string,
        coverDetails: (number | BN | string)[],
        coverPeriod: number | BN | string,
        _v: number | BN | string,
        _r: string,
        _s: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    expireCover: {
      (
        coverId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        coverId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        coverId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        coverId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    freeUpHeldCovers: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };

    getOrderHash(
      coverDetails: (number | BN | string)[],
      coverPeriod: number | BN | string,
      currency: string,
      contractAddress: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    getWithdrawableCoverNoteCoverIds(
      coverOwner: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<[BN[], string[]]>;

    getWithdrawableCoverNotesAmount(
      coverOwner: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    incidents(txDetails?: Truffle.TransactionDetails): Promise<string>;

    isValidSignature(
      hash: string,
      v: number | BN | string,
      r: string,
      s: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    makeCoverUsingNXMTokens: {
      (
        coverDetails: (number | BN | string)[],
        coverPeriod: number | BN | string,
        coverCurr: string,
        smartCAdd: string,
        _v: number | BN | string,
        _r: string,
        _s: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        coverDetails: (number | BN | string)[],
        coverPeriod: number | BN | string,
        coverCurr: string,
        smartCAdd: string,
        _v: number | BN | string,
        _r: string,
        _s: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        coverDetails: (number | BN | string)[],
        coverPeriod: number | BN | string,
        coverCurr: string,
        smartCAdd: string,
        _v: number | BN | string,
        _r: string,
        _s: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        coverDetails: (number | BN | string)[],
        coverPeriod: number | BN | string,
        coverCurr: string,
        smartCAdd: string,
        _v: number | BN | string,
        _r: string,
        _s: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    master(txDetails?: Truffle.TransactionDetails): Promise<string>;

    pool(txDetails?: Truffle.TransactionDetails): Promise<string>;

    pooledStaking(txDetails?: Truffle.TransactionDetails): Promise<string>;

    qd(txDetails?: Truffle.TransactionDetails): Promise<string>;

    sendEther: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };

    tc(txDetails?: Truffle.TransactionDetails): Promise<string>;

    td(txDetails?: Truffle.TransactionDetails): Promise<string>;

    transferAssetsToNewContract(
      arg0: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;

    verifyCoverDetails: {
      (
        from: string,
        scAddress: string,
        coverCurr: string,
        coverDetails: (number | BN | string)[],
        coverPeriod: number | BN | string,
        _v: number | BN | string,
        _r: string,
        _s: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        from: string,
        scAddress: string,
        coverCurr: string,
        coverDetails: (number | BN | string)[],
        coverPeriod: number | BN | string,
        _v: number | BN | string,
        _r: string,
        _s: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        from: string,
        scAddress: string,
        coverCurr: string,
        coverDetails: (number | BN | string)[],
        coverPeriod: number | BN | string,
        _v: number | BN | string,
        _r: string,
        _s: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        from: string,
        scAddress: string,
        coverCurr: string,
        coverDetails: (number | BN | string)[],
        coverPeriod: number | BN | string,
        _v: number | BN | string,
        _r: string,
        _s: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    verifySignature(
      coverDetails: (number | BN | string)[],
      coverPeriod: number | BN | string,
      currency: string,
      contractAddress: string,
      _v: number | BN | string,
      _r: string,
      _s: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    withdrawCoverNote: {
      (
        coverOwner: string,
        coverIds: (number | BN | string)[],
        reasonIndexes: (number | BN | string)[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        coverOwner: string,
        coverIds: (number | BN | string)[],
        reasonIndexes: (number | BN | string)[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        coverOwner: string,
        coverIds: (number | BN | string)[],
        reasonIndexes: (number | BN | string)[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        coverOwner: string,
        coverIds: (number | BN | string)[],
        reasonIndexes: (number | BN | string)[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
