/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface SwapAgentContract extends Truffle.Contract<SwapAgentInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<SwapAgentInstance>;
}

type AllEvents = never;

export interface SwapAgentInstance extends Truffle.ContractInstance {
  MAX_LIQUIDITY_RATIO(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  getSwapQuote(
    tokenAmountIn: number | BN | string,
    fromToken: string,
    toToken: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  router(txDetails?: Truffle.TransactionDetails): Promise<string>;

  methods: {
    MAX_LIQUIDITY_RATIO(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    getSwapQuote(
      tokenAmountIn: number | BN | string,
      fromToken: string,
      toToken: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    router(txDetails?: Truffle.TransactionDetails): Promise<string>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
