var MemberRoles = artifacts.require("MemberRoles");
var GovBlocksMaster = artifacts.require("GovBlocksMaster");
var Master = artifacts.require("Master");
var GBTStandardToken = artifacts.require("GBTStandardToken");
var Governance = artifacts.require("Governance");
var GovernanceData = artifacts.require("GovernanceData");
var Pool = artifacts.require("Pool");
var ProposalCategory = artifacts.require("ProposalCategory");
var SimpleVoting = artifacts.require("SimpleVoting");
var EventCaller = artifacts.require("EventCaller");
var Claims = artifacts.require("Claims");
var ClaimsData = artifacts.require("ClaimsData");
var ClaimsReward = artifacts.require("ClaimsReward");
var NXMaster = artifacts.require("NXMaster");
var NXMaster2 = artifacts.require("NXMaster2");
var MCR = artifacts.require("MCR");
var MCRData = artifacts.require("MCRData");
var NXMToken1 = artifacts.require("NXMToken1");
var NXMToken2 = artifacts.require("NXMToken2");
var NXMTokenData = artifacts.require("NXMTokenData");
var Pool1 = artifacts.require("Pool1");
var Pool2 = artifacts.require("Pool2");
var Pool3 = artifacts.require("Pool3");
var PoolData = artifacts.require("PoolData");
var Quotation = artifacts.require("Quotation");
var QuotationData = artifacts.require("QuotationData");

module.exports = function(deployer) {
    deployer.deploy(GBTStandardToken);
    deployer.deploy(EventCaller);
    deployer.deploy(GovBlocksMaster);
    deployer.deploy(GovernanceData);
    deployer.deploy(Governance);
    deployer.deploy(Pool);
    deployer.deploy(ProposalCategory);
    deployer.deploy(SimpleVoting);
    deployer.deploy(MemberRoles);
    deployer.deploy(Master);
    deployer.deploy(Claims);
    deployer.deploy(ClaimsData);
    deployer.deploy(ClaimsReward);
    deployer.deploy(NXMaster);
    deployer.deploy(NXMaster2);
    deployer.deploy(Pool1);
    deployer.deploy(Pool2);
    deployer.deploy(Pool3);
    deployer.deploy(PoolData);
    deployer.deploy(MCR);
    deployer.deploy(MCRData);
    deployer.deploy(NXMToken1);
    deployer.deploy(NXMToken2);
    deployer.deploy(NXMTokenData,"0","NXM","18","NXM");
    deployer.deploy(Quotation);
    deployer.deploy(QuotationData);
};
