var MemberRoles = artifacts.require("MemberRoles");
var GovBlocksMaster = artifacts.require("GovBlocksMaster");
var Master = artifacts.require("Master");
var GBTStandardToken = artifacts.require("GBTStandardToken");
var Governance = artifacts.require("Governance");
var GovernanceData = artifacts.require("GovernanceData");
var Pool = artifacts.require("Pool");
var ProposalCategory = artifacts.require("ProposalCategory");
var SimpleVoting = artifacts.require("SimpleVoting");
var EventCaller = artifacts.require("EventCaller");
var claims = artifacts.require("claims");
var claimsData = artifacts.require("claimsData");
var claimsReward = artifacts.require("claimsReward");
var master = artifacts.require("master");
var master2 = artifacts.require("masters2");
var mcr = artifacts.require("mcr");
var mcrData = artifacts.require("mcrData");
var nxmToken = artifacts.require("nxmToken");
var nxmToken2 = artifacts.require("nxmToken2");
var nxmTokenData = artifacts.require("nxmTokenData");
var pool = artifacts.require("pool");
var pool2 = artifacts.require("pool2");
var pool3 = artifacts.require("pool3");
var poolData = artifacts.require("poolData");
var quotation2 = artifacts.require("quotation2");
var quotationData = artifacts.require("quotationData");

module.exports = function(deployer) {
    deployer.deploy(GBTStandardToken);
    deployer.deploy(EventCaller);
    deployer.deploy(GovBlocksMaster);
    deployer.deploy(GovernanceData);
    deployer.deploy(Governance);
    deployer.deploy(Pool);
    deployer.deploy(ProposalCategory);
    deployer.deploy(SimpleVoting);
    deployer.deploy(MemberRoles);
    deployer.deploy(Master);
    deployer.deploy(claims);
    deployer.deploy(claimsData);
    deployer.deploy(claimsReward);
    deployer.deploy(master);
    deployer.deploy(master2);
    deployer.deploy(pool);
    deployer.deploy(pool2);
    deployer.deploy(pool3);
    deployer.deploy(poolData);
    deployer.deploy(mcr);
    deployer.deploy(mcrData);
    deployer.deploy(nxmToken);
    deployer.deploy(nxmToken2);
    deployer.deploy(nxmTokenData,"0","NXM","18","NXM");
    deployer.deploy(quotation2);
    deployer.deploy(quotationData);
};
