const C_REGISTRY = 1;
const C_GOVERNOR = 2;
const C_TOKEN = 4;
const C_TOKEN_CONTROLLER = 8;
const C_POOL = 16;
const C_MEMBER_ROLES = 32;
const C_COVER = 64;
const C_COVER_PRODUCTS = 128;
const C_STAKING_PRODUCTS = 256;
const C_RAMM = 512;
const C_SAFE_TRACKER = 1024;
const C_LIMIT_ORDERS = 2048;
const C_STAKING_NFT = 4096;
const C_COVER_NFT = 8192;
const C_SWAP_OPERATOR = 16384;
const C_ASSESSMENT = 32768;
const C_CLAIMS = 65536;

const PAUSE_GLOBAL = 1;
const PAUSE_RAMM = 2;
const PAUSE_SWAPS = 4;
const PAUSE_MEMBERSHIP = 8;
const PAUSE_ASSESSMENTS = 16;
const PAUSE_CLAIMS_PAYOUT = 32;

module.exports = {
  C_REGISTRY,
  C_GOVERNOR,
  C_TOKEN,
  C_TOKEN_CONTROLLER,
  C_POOL,
  C_MEMBER_ROLES,
  C_COVER,
  C_COVER_PRODUCTS,
  C_STAKING_PRODUCTS,
  C_RAMM,
  C_SAFE_TRACKER,
  C_LIMIT_ORDERS,
  C_STAKING_NFT,
  C_COVER_NFT,
  C_SWAP_OPERATOR,
  C_ASSESSMENT,
  C_CLAIMS,
  PAUSE_GLOBAL,
  PAUSE_RAMM,
  PAUSE_SWAPS,
  PAUSE_MEMBERSHIP,
  PAUSE_ASSESSMENTS,
  PAUSE_CLAIMS_PAYOUT,
};
